### PR TITLE
Michelson guidlines june 11

### PR DESCRIPTION
**Pull request by davidamichelson**

### CODE REVIEW

**Comment by davidamichelson** [comment]
@wsalesky I've merged my changes in the documentation into main, do I also merge to build or will the webhooks grab the new file? Thanks!

**Comment by wsalesky** [comment]
Webhooks should grab it. If you do not see it let me know and I will take a look at the webhooks

**Comment by davidamichelson** [comment]
Looks like webhooks didn't work.

**Comment by wsalesky** [comment]
I will run a build. And then check the webhooks, looks like they are not reseting correctly after the build process.

**Comment by davidamichelson** [comment]
Thanks!

**Comment by wsalesky** [comment]
@davidamichelson do you see your changes?

**Pull request merged**
